name: VPool Admin, Proxy and Rewards test
on:
  pull_request:
    paths:
      - "test/*.js"
      - "contracts/pool/*.sol"

jobs:
  paycer-pool-test:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running tests for Paycer Pool Admin
        run: npm test "test/paycer-pool-admin.js"

      - name: Running tests for Paycer Pool Proxy upgrade
        run: npm test "test/paycer-pool-proxy.js"

      - name: Running tests for Paycer PoolRewards
        run: npm test "test/pool-rewards.js"

      - name: Running tests for Paycer Pool Accountant Proxy upgrade
        run: npm test "test/pool-accountant-proxy.js"
