name: vDAI Strategies Migration and Reward
on:
  pull_request:
    paths:
      - "test/vdai/migration.js"
      - "test/vdai/reward.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/aave/AaveCore.sol"
      - "contracts/strategies/aave/AaveStrategy.sol"
      - "contracts/strategies/aave/AaveStrategyDAI.sol"
      - "contracts/strategies/compound/CompoundStrategy.sol"
      - "contracts/strategies/compound/CompoundStrategyDAI.sol"

jobs:
  vdai-test:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running vDAI Strategies Migration tests
        run: npm test "test/vdai/migration.js"

      - name: Running vDAI Reward tests
        run: npm test "test/vdai/reward.js"
