name: vETH with Maker strategies
on:
  pull_request:
    paths:
      - "test/veth/aave_maker-compound_maker.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/maker/MakerStrategy.sol"
      - "contracts/strategies/maker/CollateralManager.sol"
      - "contracts/strategies/aave/AaveCore.sol"
      - "contracts/strategies/maker/AaveMakerStrategy.sol"
      - "contracts/strategies/maker/AaveMakerStrategyETH.sol"
      - "contracts/strategies/maker/CompoundMakerStrategy.sol"
      - "contracts/strategies/maker/CompoundMakerStrategyETH.sol"

jobs:
  veth-maker-strategies-test:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running vETH with Aave Maker and Compound Maker
        run: npm test "test/veth/aave_maker-compound_maker.js"
