name: vETH with Compound Leverage
on:
  pull_request:
    paths:
      - "test/veth/compound-leverage.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/compound/CompoundLeverageStrategy.sol"
      - "contracts/strategies/compound/CompoundLeverageStrategyETH.sol"

jobs:
  veth-compound-leverage-test:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running vETH with Compound Leverage
        run: npm test "test/veth/compound-leverage.js"
