name: vETH with Compound XY
on:
  pull_request:
    paths:
      - "test/veth/compound-xy.js"
      - "test/veth/compound.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/CompoundStrategy.sol"
      - "contracts/strategies/compound/CompoundXYStrategy.sol"
      - "contracts/strategies/compound/CompoundXYStrategyETH.sol"

jobs:
  veth-compound-xy-test:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running vETH with Compound XY
        run: npm test "test/veth/compound-xy.js"

      - name: Running vETH with Compound
        run: npm test "test/veth/compound.js"
