name: vfrDAI VFR
on:
  pull_request:
    paths:
      - "test/vfrdai/*.js"
      - "contracts/pool/*.sol"
      - "contracts/strategies/compound/vfr/*.sol"
      - "contracts/strategies/convex/vfr/*.sol"

jobs:
  vfrdai-pool-test:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running vfrDAI VFR deterministic tests
        run: npm test "test/vfrdai/vfr-deterministic.js"

      - name: Running vfrDAI VFR non-deterministic tests
        run: npm test "test/vfrdai/vfr-nondeterministic.js"
