name: vUSDC with Curve 3Pool
on:
  pull_request:
    paths:
      - "test/vusdc/crv-3pool.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/curve/CrvBase.sol"
      - "contracts/strategies/curve/Crv3x.sol"
      - "contracts/strategies/curve/Crv3PoolStrategyBase.sol"
      - "contracts/strategies/curve/3Pool/Crv3PoolStrategy.sol"
      - "contracts/strategies/curve/3Pool/Crv3PoolStrategyUSDC.sol"

jobs:
  vusdc-curve3p-strategy-test:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running tests for vUSDC with Curve 3Pool
        run: npm test "test/vusdc/crv-3pool.js"
