name: vUSDT with Alpha Lend
on:
  pull_request:
    paths:
      - "test/vusdt/alpha-lend.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/alpha/AlphaLendStrategy.sol"
      - "contracts/strategies/alpha/AlphaLendStrategyUSDT.sol"

jobs:
  vusdt-alphalend-strategy-test:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running tests for vUSDT with Alpha Lend
        run: npm test "test/vusdt/alpha-lend.js"
