name: vUSDC with AaveV1 Aave
on:
  pull_request:
    paths:
      - "test/vusdc/aaveV1-aave.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/aave/AaveCore.sol"
      - "contracts/strategies/aave/AaveStrategy.sol"
      - "contracts/strategies/aave/AaveStrategyUSDC.sol"
      - "contracts/strategies/aave/AaveV1Strategy.sol"
      - "contracts/strategies/aave/AaveV1StrategyUSDC.sol"

jobs:
  vusdc-aaveV1-aave-test:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running vUSDC AaveV1 and Aave
        run: npm test "test/vusdc/aaveV1-aave.js"
